name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: >
            cargo-tarpaulin
      # - name: Install docker-compose
      #   run: |
      #     curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     chmod +x /usr/local/bin/docker-compose
      - name: Start postgres database
        run: |
          cd packages/datajoint-core/tests
          ls
          pwd
          docker-compose -f docker-compose-test.yml up -d 
          docker exec tests_postgres_13_1 bash -c "until pg_isready; do sleep 1; done"
          until nc -z -v -w30 localhost 3306; do echo "Waiting for database connection...";sleep 5;done;

      - name: Run tests and upload coverage
        run: |
          cargo tarpaulin --verbose --coveralls X5IJ9L48tT10necJAKzAkaMkHtpwDp43G

      # - name: run tests
      #   run: |
      #     cargo test

      - name: clean
        run: |
          cd packages/datajoint-core/tests
          docker-compose -f docker-compose-test.yml rm

      #   are we going to upload these any where?
      # - name:                   Upload to codecov.io
      #   uses:                   codecov/codecov-action@v2
      #   with:
      #     # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
      #     fail_ci_if_error:     true
