name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      # do we want to use the nightly version or not?
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install docker-compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start test databases
        run: |
          cd packages/datajoint-core/tests
          ls
          docker-compose -f docker-compose-test.yml up

      - name: Run tests and upload coverage
        run: |
          cargo tarpaulin --verbose --coveralls ${{ secrets.GITHUB_TOKEN }}

      #   are we going to upload these any where?
      # - name:                   Upload to codecov.io
      #   uses:                   codecov/codecov-action@v2
      #   with:
      #     # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
      #     fail_ci_if_error:     true
