name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install docker-compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      # - name: install tarpaulin
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: >
      #       cargo-tarpaulin

      - name: Start postgres database
        run: |
          cd packages/datajoint-core/tests
          ls
          pwd
          docker-compose -f docker-compose-test.yml up -d 
          docker exec tests_postgres_13_1 bash -c "until pg_isready; do sleep 1; done"
          until nc -z -v -w30 localhost 3306; do echo "Waiting for database connection...";sleep 5;done;

      - name: Run tests and upload coverage
        run: |
          cargo tarpaulin --verbose --coveralls ${{ secrets.COVERALLS_KEY }}

      - name: clean
        run: |
          cd packages/datajoint-core/tests
          docker-compose -f docker-compose-test.yml rm
